#!/bin/bash
# Usage: ./ka "kubectl get ns | grep dev"

if [ $# -eq 0 ]; then
  echo "Usage: $0 \"kubectl command\""
  exit 1
fi

COMMAND="$1"

# Loop through all contexts
kubectl config get-contexts -o name | while read -r ctx; do
  
  kubectl config use-context "$ctx" >/dev/null 2>&1
  # Get current cluster name
  CLUSTER_NAME=$(kubectl config view --minify -o jsonpath='{.clusters[0].name}')
  echo -e "\n\033[1;34m===\033[0m \033[1;33m[$CLUSTER_NAME]\033[0m \033[1;34m===\033[0m"
  
  # Run the command and capture output
  eval "$COMMAND"
done
